version: "3"
services:
  jobmanager:
    container_name: jobmanager
    build: ./Flink_server
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager     
    volumes: 
      - ./Flink_server:/usr/script/flink
    privileged: true
    networks:
      default_bridge:
        ipv4_address: 172.22.0.7
  taskmanager:
    build: ./Flink_server
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2  
    networks:
      default_bridge:
        ipv4_address: 172.22.0.6
  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.22.0.8:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=1248576000
    user: "root"
    networks:
      default_bridge:
        ipv4_address: 172.22.0.8
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui_elk
    links:
      - kafka:kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=my_kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.22.0.8:9092
    networks:
      default_bridge:
        ipv4_address: 172.22.0.9 
  python:
    build: ./python_server
    container_name: python
    networks:
      default_bridge:
        ipv4_address: 172.22.0.10
    volumes:
      - ./python_server:/usr/script/python
      - ./data:/usr/script/python/data
networks:
  default_bridge:
    ipam:
      config:
        - subnet: 172.22.0.0/16